import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/custom/header";
import UserContextProvider from "@/components/context/UsercontextProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <UserContextProvider>
          <Header></Header>
          <main>{children}</main>
        </UserContextProvider>
      </body>
    </html>
  );
}
